Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,10 +28,11 @@ jobs:
           SPFX_SKIP_FEATURE_DEPLOYMENT: true
           NODE_OPTIONS: --max-old-space-size=8192
         run: |
-          set -e
           gulp clean
-          gulp bundle --ship || exit 0
+          gulp bundle --ship
           gulp package-solution --ship
+          echo "Checking for .sppkg file..."
+          ls -la sharepoint/solution/ || echo "Solution folder not found"
       
       - name: Upload artifact
         uses: actions/upload-artifact@v4
